#!/bin/bash

# Impostazioni per una macchina singola con 1 GPU
DEFAULT_GPUS_PER_NODE=1
DEFAULT_MASTER_ADDR="127.0.0.1"
DEFAULT_MASTER_PORT=25001

echo "Esecuzione locale (no SLURM)"

# Nome run e directory di output
RUN_NAME=${RUN_NAME:-$DEFAULT_RUN_NAME}
echo "RUN_NAME = $RUN_NAME"

OUTPUT_DIR=${OUTPUT_DIR:-"/home/workspace/VILA/runs/train/$RUN_NAME"}
echo "OUTPUT_DIR = $OUTPUT_DIR"

# Imposta variabili per Weights & Biases
export WANDB_PROJECT="vila"
export WANDB_DIR=$OUTPUT_DIR
export WANDB_RUN_ID=$RUN_NAME
export WANDB_NAME=$RUN_NAME
export WANDB_RESUME="allow"

# Un solo nodo e una sola GPU
NNODES=1
echo "NNODES = $NNODES"

NODES="localhost"
echo "NODES = $NODES"

NODE_RANK=0
echo "NODE_RANK = $NODE_RANK"

GPUS_PER_NODE=1
echo "GPUS_PER_NODE = $GPUS_PER_NODE"

MASTER_ADDR=$DEFAULT_MASTER_ADDR
echo "MASTER_ADDR = $MASTER_ADDR"

MASTER_PORT=$DEFAULT_MASTER_PORT
echo "MASTER_PORT = $MASTER_PORT"

# Batch size globale e per GPU
GLOBAL_TRAIN_BATCH_SIZE=${GLOBAL_TRAIN_BATCH_SIZE:-1}  # esempio
echo "GLOBAL_TRAIN_BATCH_SIZE = $GLOBAL_TRAIN_BATCH_SIZE"

GRADIENT_ACCUMULATION_STEPS=${GRADIENT_ACCUMULATION_STEPS:-1}
echo "GRADIENT_ACCUMULATION_STEPS = $GRADIENT_ACCUMULATION_STEPS"

PER_DEVICE_TRAIN_BATCH_SIZE=$((GLOBAL_TRAIN_BATCH_SIZE / NNODES / GPUS_PER_NODE / GRADIENT_ACCUMULATION_STEPS))
echo "PER_DEVICE_TRAIN_BATCH_SIZE = $PER_DEVICE_TRAIN_BATCH_SIZE"

# (opzionale) controllo su batch massimo
if [ -n "$MAX_PER_DEVICE_TRAIN_BATCH_SIZE" ] && [ "$PER_DEVICE_TRAIN_BATCH_SIZE" -gt "$MAX_PER_DEVICE_TRAIN_BATCH_SIZE" ]; then
    echo "PER_DEVICE_TRAIN_BATCH_SIZE is greater than MAX_PER_DEVICE_TRAIN_BATCH_SIZE"
    exit 1
fi

# Variabili ambiente per stabilità CUDA
export NCCL_IB_SL=1
export CUDA_DEVICE_MAX_CONNECTIONS=1
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export OMP_NUM_THREADS=1
